# Generated by Django 3.1.3 on 2020-11-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventcategory',
            table='event_categories',
        ),
    ]
