# Generated by Django 3.1.3 on 2020-11-11 06:31

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201108_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.get_image_path),
        ),
    ]
