# Generated by Django 3.1.3 on 2020-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
